#!/bin/bash

function hc() {
    herbstclient "$@"
}

# Theme
# wallpaper
xsetroot -solid \#248
# colors
color_active='#268bd2'
color_inactive='#93a1a1'
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set window_border_width 3
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#66abf2'
hc set always_show_frame 1
hc set frame_gap 2
hc set frame_bg_transparent 1
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0

# Other setup.
hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvtc
hc keybind $Mod-space spawn dmenu-launch
hc keybind $Mod-Escape spawn ${HOME}/bin/lock
hc keybind $Mod-Shift-Escape spawn ${HOME}/bin/suspend
hc keybind $Mod-w spawn hcsrc
hc keybind $Mod-m spawn ${HOME}/bin/monitors
hc keybind $Mod-x spawn ${HOME}/bin/fx

# Volume bindings
hc keybind $Mod-Alt-j spawn ${HOME}/bin/vol down
hc keybind $Mod-Alt-k spawn ${HOME}/bin/vol up
hc keybind $Mod-Alt-l spawn ${HOME}/bin/vol toggle
# Dedicated audio keys
hc keybind XF86AudioRaiseVolume spawn ${HOME}/bin/vol up
hc keybind XF86AudioLowerVolume spawn ${HOME}/bin/vol down
hc keybind XF86AudioMute spawn ${HOME}/bin/vol toggle
hc keybind XF86AudioMicMute spawn ${HOME}/bin/vol toggle-mic

# Media keys
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind $Mod-Alt-slash spawn playerctl play-pause
hc keybind $Mod-Alt-comma spawn playerctl previous
hc keybind $Mod-Alt-period spawn playerctl next

# Brightness bindings.
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10
hc keybind Shift+XF86MonBrightnessDown spawn xbacklight -dec 1
hc keybind Shift+XF86MonBrightnessUp spawn xbacklight -inc 1
hc keybind $Mod-minus spawn xbacklight -dec 10
hc keybind $Mod-equal spawn xbacklight -inc 10
hc keybind Shift+$Mod-minus spawn xbacklight -dec 1
hc keybind Shift+$Mod-equal spawn xbacklight -inc 1

# Wifi kill switch
hc keybind XF86WLAN spawn notify-send -i notification-network-wireless-off "WiFi toggled"

# Grab a shell
hc keybind Mod4+e spawn sidebar 'zsh'
hc keybind Mod4+t spawn sidebar 'task; task shell'
hc keybind Mod4+n spawn sidebar 'vim ~/notes/'

# tags
TAG_NAMES=( {1..9} 0 )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" 2>/dev/null || true
for i in ${!TAG_NAMES[@]} ; do
    key="${TAG_KEYS[$i]}"
    name="${TAG_NAMES[$i]}"
    hc add $name
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Right  use_index +1
hc keybind $Mod-Left   use_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Tab use_previous
hc keybind $Mod-backslash cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind Alt-Tab          cycle_all +1
hc keybind Alt-Shift-Tab    cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc set focus_follows_mouse 0

# rules
hc unrule -F
hc rule focus=on # Normally focus new windows.
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' not instance="gnucash" pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype="_NET_WM_WINDOW_TYPE_UTILITY" class="VidyoDesktop" manage=off

# find the panel
pkill panel.sh
~/.config/herbstluftwm/panel.sh &

function ensure() {
    pgrep $1 || $1 &
}

ensure stalonetray
ensure conky
ensure nm-applet
ensure twmnd
