#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

# Get location of autostart file
BASE="$(dirname $0)"

hc lock
hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-space spawn dmenu_run
hc keybind $Mod-Escape spawn ${HOME}/bin/lock
hc keybind $Mod-Shift-Escape spawn ${HOME}/bin/suspend
hc keybind $Mod-n spawn renametag
hc keybind $Mod-w spawn hcsrc

# Volume bindings
hc keybind $Mod-Alt-j spawn amixer set Master,0 5%-
hc keybind $Mod-Alt-k spawn amixer set Master,0 5%+
hc keybind $Mod-Alt-l spawn amixer set Master,0 toggle
# And the labeled Fn+keys
hc keybind XF86AudioLowerVolume spawn amixer set Master,0 5%-
hc keybind XF86AudioRaiseVolume spawn amixer set Master,0 5%+
hc keybind XF86AudioMute spawn amixer set Master,0 toggle
# Media bindings.
hc keybind XF86AudioPlay spawn spotify-remote playpause
hc keybind XF86AudioNext spawn spotify-remote next
hc keybind XF86AudioPrev spawn spotify-remote prev
hc keybind XF86AudioStop spawn spotify-remote stop

# tags
TAG_NAMES=( {1..9} 0 )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    key="${TAG_KEYS[$i]}"
    name="${TAG_NAMES[$i]}"
    hc add $name
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Right  use_index +1
hc keybind $Mod-Left   use_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Tab cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind Alt-Tab          cycle_all +1
hc keybind Alt-Shift-Tab    cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc set focus_follows_mouse 0

# colors
color_active='#268bd2'
color_inactive='#93a1a1'
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set window_border_width 2
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#268bd2'
hc set always_show_frame 1
hc set frame_gap 3
hc set frame_bg_transparent 1

# rules
hc unrule -F
hc rule focus=on # Normally focus new windows.
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class~'Spotify' tag=0

# Set up multi monitors
${HOME}/bin/monfix
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    $panel $monitor &
done

# Wallpapers!
feh -z --bg-fill ~/Dropbox/Apps/Desktoppr/*

# unlock, just to be sure
hc unlock
